server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
      
spring:
  application:
    name: gatewat-server
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
gateway:
  uri:
    product-service: http://product-service:8087/
    cart-service: http://cart-service:8088/
