server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: gatewat-server
gateway:
  uri:
    product-service: http://localhost:8087/
    cart-service: http://localhost:8088/
