server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
      
spring:
  application:
    name: gatewat-server
gateway:
  uri:
    product-service: http://product-service:8087/
    cart-service: http://cart-service:8088/
