spring:
  profiles:
    active: "@activeProfile@"
    
logging:
  level:
    root: INFO
    
jwt:
  key: SECRETKEYSECRSECRETKEYSECRETKEYSECRETKEYETSSECRETKEYSECRETKEYSECRETKEYECRETKEYSECRETKEYSECRETKEYKEYSECRETKEY